import os

import sourcer


project_home = os.path.dirname(__file__)


def main():
    with open(os.path.join(project_home, 'grammar.txt')) as f:
        description = f.read()

    grammar = sourcer.Grammar(description, include_source=True)

    with open(os.path.join('wasmtree', 'parser.py'), 'w') as f:
        f.write(f'# Generated by ../generate_parser.py\n')
        f.write(grammar._source_code)


if __name__ == '__main__':
    main()
